package maru.core.model.net;

public enum NetworkMessageID
{
    SCENARIO_CREATED,
    SCENARIO_ADDED,
    SCENARIO_REMOVED,

    ELEMENT_ADDED,
    ELEMENT_REMOVED,
    ELEMENT_RENAMED,
    ELEMENT_COMMENTED,
    ELEMENT_COLOR_CHANGED,
    ELEMENT_IMAGE_CHANGED,

    CENTRAL_BODY_IMAGE_CHANGED,
    CENTRAL_BODY_GM_CHANGED,
    CENTRAL_BODY_EQUATORIAL_RADIUS_CHANGED,
    CENTRAL_BODY_FLATTENING_CHANGED,

    GROUNDSTATION_INITIAL_COORDINATE_CHANGED,
    SPACECRAFT_INITIAL_COORDINATE_CHANGED,

    PROPAGATABLES_TIME_CHANGED,

    TIMEPOINT_START_CHANGED,
    TIMEPOINT_STOP_CHANGED,
    TIMEPOINT_CURRENT_CHANGED,

    TIMEPOINT_ADDED,
    TIMEPOINT_REMOVED,
    TIMEPOINT_CHANGED
}
